import { AppProvider } from "../components/AppContext";
import { EdgeStoreProvider } from "../libs/edgestore";
import { Roboto } from "next/font/google";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ScrollToTopButton from "../components/layout/ScrollToTopButton";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <EdgeStoreProvider>
          <AppProvider>
            <Toaster />
            <Header />
            <main className="ml-64 p-4">
              {/* ml-64 applies a left margin to compensate for the fixed sidebar width */}
              {children}
              <ScrollToTopButton />
            </main>
            <Footer />
          </AppProvider>
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
